branch-defaults:
  default:
    environment: sinatrapp-dev
    group_suffix: null
global:
  application_name: fakeappforaws2
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
